# Generated by Django 3.2.6 on 2021-09-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('sugar', models.FloatField()),
                ('lipid', models.FloatField()),
                ('dietary_fiber', models.FloatField()),
                ('salt', models.FloatField()),
                ('is_bad', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.company')),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.RemoveField(
            model_name='diary',
            name='ate_food',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='diary',
            name='ate_meal',
            field=models.ManyToManyField(blank=True, db_table='diary_ate_meal', related_name='ate_meal', to='api.Meal'),
        ),
    ]
