# Generated by Django 3.2.6 on 2021-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210909_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dietary_fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lipid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='salt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
