# Generated by Django 3.2.6 on 2021-09-12 01:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_meal_path),
        ),
    ]
