# Generated by Django 3.2.6 on 2021-09-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_meal_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
