# Generated by Django 3.2.6 on 2021-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_meal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
