version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - USE_PTVSD
    volumes:
      - ./backend:/code/
    tty: true
    ports:
      - '8000:8000'
#    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    command: /usr/local/bin/gunicorn project.wsgi:application -w 2 -b :8000 --reload
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'Asia/Tokyo'
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - '3000:3000'
    command: ['npm', 'start']