version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - USE_PTVSD
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    volumes:
      - ./backend:/code/
    tty: true
    ports:
      - '8000:8000'
      - '8888:8888'
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'Asia/Tokyo'
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
