# Generated by Django 3.2.6 on 2021-09-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsbs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('company_id', 'name'), name='meal_name_unique'),
        ),
    ]
