# Generated by Django 3.2.6 on 2021-11-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('order_column_no', models.IntegerField()),
                ('order_date', models.DateField()),
                ('item_name', models.CharField(max_length=512)),
                ('store_name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'amazon_purchase_history',
            },
        ),
        migrations.AddConstraint(
            model_name='amazonpurchasehistory',
            constraint=models.UniqueConstraint(fields=('order_number', 'order_column_no'), name='order_number_unique'),
        ),
    ]
