# Generated by Django 3.2.6 on 2021-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsbs', '0002_meal_meal_name_unique'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['company_id', 'name'], name='meals_company_7ad7c4_idx'),
        ),
    ]
