# Generated by Django 3.2.6 on 2021-11-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsbs', '0002_auto_20211109_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonpurchasehistory',
            old_name='order_column_no',
            new_name='order_row',
        ),
    ]
