# Generated by Django 3.2.6 on 2021-09-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsbs', '0004_alter_diary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='total_calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
